name = "Hugo Microblog"
license = "MIT"
licenselink = "https://github.com/mandarvaze/hugo-microblog/blob/main/LICENSE.md"
description = "A personal, minimal blog theme for Hugo."
homepage = "https://microblog.desipenguin.com/about/"
tags = ["blog", "personal", "minimal", "microblog", "photoblog", "linkblog", "responsive"]
features = ["Microblog", "Photoblog", "Blog", "Flickr Photo Stream", "Personal Blog", "Link Blog", "Responsive"]
min_version = 0.14

[author]
  name = "Mandar Vaze"
  homepage = "https://microblog.desipenguin.com/about/"
